### ISSUE TITLE
`.reloc` with complex offset does not work with `ia16-elf-as --32-segelf`

### ISSUE THREAD

**Issue by tkchia** [tkchia/binutils-ia16#6] opened 2020-04-28 15:33 UTC
```
$ cat bar.s
	.hword	0
	.reloc	.-2, R_386_SEG16, bar
$ ia16-elf-as --32-segelf bar.s
bar.s: Assembler messages:
bar.s:2: Error: invalid offset expression
```

**Comment by asiekierka** [comment] 2022-12-09 20:05
Some insights:

- In segelf mode, the fake label `L0` emitted as part of the `.reloc` is placed in the section `*ABS*`, while without segelf it's correctly placed in the section `.text`, where the rest of the code resides.
- No-oping `i386_elf_symbol_new_hook` seems to correctly put `L0` in `.text`.

**Comment by asiekierka** [comment] 2022-12-22 09:25
In `i386_elf_find_segelf_aux_symbol`, `S_GET_VALUE (symbolP) == 0` has side effects. Removing that specific call causes the compilation of the above example to succeed, but it breaks other scenarios, seemingly involving relative jumps...

**Comment by asiekierka** [comment] 2023-05-30 21:23
Potential fix, in `i386_elf_find_segelf_aux_symbol (symbolS *symbolP, char which)`:

```
-      else if (! S_IS_EXTERNAL (symbolP) && S_GET_VALUE (symbolP) == 0)
+      else if (! S_IS_EXTERNAL (symbolP) && symbol_get_frag (symbolP) == &zero_address_frag)
        {
+          if (bfd_is_local_label_name (stdoutput, name))
+            return symbolP;
```

The first line change removes side effects from `S_GET_VALUE` (if I understand correctly, `&zero_address_frag` should be typically used for section symbols); the second line change fixes the code applying for local label names.

**Comment by tkchia** [comment] 2023-05-31 18:23
Hello @asiekierka,

Thanks &mdash; let me try using `symbol_get_frag (.)` instead.

I am not sure the `bfd_is_local_label_name (`...`)` check is really needed.  The code later checks whether the symbol name is exactly the same as the section name.

(Perhaps I should try to write a test case for a situation where a section name "looks like" an ELF-style local symbol, e.g. it has the form `.L`... or `_.L`... or `L0☺`... etc.  The assembler should probably not weird out in such a condition.)

Thank you!

**Comment by asiekierka** [comment] 2023-05-31 18:33
For `name` == `L0`, `seg->symbol->name` is `*GAS 'expr' section*`, I assume it's the constant value `expr_section`; that is not covered by the previous code, and it seems the later code causes problems.

The reason the previous code worked is that the `S_GET_VALUE (symbolP)` call turned the section from `expr_section` to `absolute_section` in the value resolving process.

**Comment by asiekierka** [comment] 2023-05-31 18:35
Commenting out the workaround code below:

```
  /*
   *    "jobs.s: Internal error in symbol_new at ../../binutils-ia16/gas/
   *     symbols.c:228."
   * If this looks really really like a local symbol, then try to flesh it
   * out immediately.
   */
```
also seems to work (combined with `symbol_get_frag (.)` of course), but I do not have the necessary test case to reproduce this crash.

Apologies for the low quality of investigation - I'm still a junior when it comes to hacking on the GNU toolchains...

**Comment by asiekierka** [comment] 2023-05-31 18:57
I've added my proposed patch here: https://github.com/tkchia/binutils-ia16/pull/13/commits/2eb6b79fe1b3e91d2a1a617174c5ff82dc260b86

(I'm back to work on DWARF2 support - I'm writing a comment clarifying the current state there)

**Comment by asiekierka** [comment] 2023-05-31 19:47
Reproduction scenario for the introduced bug:

```
        .intel_syntax noprefix
        mul word ptr [rand_seed_lo]
```

`ia16-elf-as --32-segelf file.s`

**Comment by tkchia** [comment] 2023-05-31 19:57
@asiekierka : let me look into this.  Thank you!

**Comment by tkchia** [comment] 2023-05-31 20:53
@asiekierka : should be fixed now, thanks!

**Comment by asiekierka** [comment] 2023-06-01 04:40
After this patch, there are no regressions across my suite of projects. If there are likewise no regressions across your projects, I believe this can probably be closed. Thank you very much!

**Closed as completed** 2023-06-01 21:07 UTC
Labels: bug
